### PR TITLE
Highlight.js from npm

### PR DESCRIPTION
**Pull request by kamilkisiela**
So Meteor@1.3 at least.

@stubailo Why? Because `mdg:tutorial-diff-box` depends on it and at the moment there is no support for typescript. I could move diffBox to use node modules but it would take a lot more time :cry:

### CODE REVIEW

**Comment by stubailo** [comment]
Hmm, we could publish a version of this that works only in Meteor 1.3! And then maybe the app itself should install highlight.js and this package just does the work of integrating it with the Blaze markdown helper?

**Comment by kamilkisiela** [comment]
Sure! :+1:

**Comment by kamilkisiela** [comment]
We could do something like this:

``` js
if(isIE8)
  return;

try {
  require('highlight.js');
} catch (e) {
  throw new Error('Stop! Highlights time');
}

if (Package.markdown) {
  var decode;
```

@stubailo Do we take this way?

**Comment by stubailo** [comment]
I think using highlight.js from npm is definitely a better idea in 2017!

**Pull request closed without merging**
