### PR TITLE
Support chuangbo:marked

### PR DESCRIPTION
**Pull request by zimme**
Basic support for `chuangbo:marked`

### CODE REVIEW

**Comment by stubailo** [comment]
Does that package have any option to set the language manually? It would be good to support that as well.

**Comment by zimme** [comment]
``` js
// I haven't tested this
marked.setOptions({
  highlight: function(code, lang) {
    hljs.highlight(lang, code).value;
  }
});
```

I can update the PR to use the `lang` option if it's not undefined.

**Comment by zimme** [comment]
Updated PR to use manual language setting if available.

**Comment by stubailo** [comment]
I'm on vacation till Thursday, I'll merge then.

**Comment by zimme** [comment]
No problem. Have a great time and make sure you do at least one stupid thing :stuck_out_tongue_closed_eyes:

**Comment by zimme** [comment]
Added `try-catch` to fall back on auto detection of highligh doesn't support the specified language.

But maybe just showing the code without highlighting is better in this case?

**Comment by stubailo** [comment]
Yeah I think it shouldn't highlight - sometimes it picks something weird and your code looks weird. I think there should be an option to turn it off. But maybe there is a special file extension like `txt` that can work for this? IDK. The behaviour that would be consistent with the `markdown` support is to only highlight when a language is passed.

**Comment by zimme** [comment]
But this snippet leads me to think that the `markdown` support actually falls back on autodetect if lang isn't provided.

``` js
if (lang) {
  return hljs.highlight(lang, decode(codeWithEntities))
} else {
  return hljs.highlightAuto(decode(codeWithEntities));
}
```

and also have the problem which I solved with the `try-catch`

**Comment by stubailo** [comment]
Oh, whoa. OK I'm totally wrong! I guess we should add the try catch to my code as well.

**Comment by stubailo** [comment]
Published at 1.1.0!

**Pull request merged**
